version: '3.7'

services:

    wordpress:
        image: wordpress
        volumes:
            - ./new-user-approve.php:/var/www/html/wp-content/plugins/new-user-approve/new-user-approve.php
            - ./admin:/var/www/html/wp-content/plugins/new-user-approve/admin
            - ./includes:/var/www/html/wp-content/plugins/new-user-approve/includes
            - ./localization:/var/www/html/wp-content/plugins/new-user-approve/localization
        ports:
            - 8061:80
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wpuser
            WORDPRESS_DB_PASSWORD: password
            WORDPRESS_DB_NAME: sandbox
            WORDPRESS_DEBUG: "true"
        restart: always
        depends_on:
            - db

    db:
        image: mysql:5.7
        restart: always
        volumes:
            - ./.docker/storage/wordpress:/var/lib/mysql
        ports:
            - 23302:3306
        environment:
            MYSQL_DATABASE: sandbox
            MYSQL_USER: wpuser
            MYSQL_PASSWORD: password
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
